stages:
  - build
  - build-docker
  - webhook

build:
  stage: build
  image: gitlab.cyberspike.top:5050/docker/python:3.12
  script:
    - sed -i 's|http://deb.debian.org/debian|http://mirrors.huaweicloud.com/debian|g; s|http://deb.debian.org/debian-security|http://mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list.d/debian.sources && apt-get update && apt-get install -y patchelf
    - pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple
    - pip install build
    - python -m build --wheel
  tags:
    - docker
  artifacts:
    paths:
      - dist/

build-docker:
  stage: build-docker
  image: gitlab.cyberspike.top:5050/docker/docker:dind
  services:
    - name: gitlab.cyberspike.top:5050/docker/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  tags:
    - docker
  script:
    - docker build -t gitlab.cyberspike.top:5050/aszl/diamond-shovel/diamond-shovel:$(echo -n "$CI_COMMIT_REF_NAME" |  sed 's/[^a-zA-Z0-9._-]/_/g') .
    - docker push gitlab.cyberspike.top:5050/aszl/diamond-shovel/diamond-shovel:$(echo -n "$CI_COMMIT_REF_NAME" |  sed 's/[^a-zA-Z0-9._-]/_/g')
webhook:
  stage: webhook
  image: gitlab.cyberspike.top:5050/docker/alpine/curl:8.9.1
  script:  |
    curl -X POST -H "Content-Type: application/json" -d '{"project_name": "diamond-shovel", "branch_name": "'$(echo -n "$CI_COMMIT_REF_NAME" |  sed 's/[^a-zA-Z0-9._-]/_/g')'"}' http://workbench.dev.cyberspike.top:2333/update_branch
    curl -X POST --fail -F token=$CI_JOB_TOKEN -F ref=dev https://gitlab.cyberspike.top/api/v4/projects/65/trigger/pipeline
  tags:
    - docker
