services:
  diamond_shovel_test:
    image: diamond_shovel_test
    build:
      context: .
    volumes:
      - .:/data
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - internal_network
    entrypoint: ["/usr/bin/python3", "/data/wrapped_main.py", "-t", "中山市中龙计算机技术有限公司", "-m", "cyberspike.top"]
    working_dir: /data

  diamond_shovel_package_deobf: &package_deobf
    image: diamond_shovel_package
    build:
      context: .
      dockerfile: package.Dockerfile
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/data
    entrypoint: ["/bin/bash", "/data/building/debian_bookworm.sh", "diamond-shovel"]
    working_dir: /data

networks:
  internal_network:
    driver: bridge
